### ISSUE TITLE
Hook scripts missing IOCAGE_ env variables

### ISSUE THREAD

**Issue by urosgruber** [bsdci/libioc#342]
I'm not sure if feature was changed but I noticed new folder **launch-scripts** including some shell scripts and all are also exposed inside jail as well. I can find any info of how this can be used or what is the case for this. But after some testing again with latest changes I noticed there is no `IOCAGE_` evn variables present inside pre/post-start and pre/post-stop scripts.

Am I missing something or configuration changed. I usually set this scripts via
`ioc set exec_poststart=/root/scripts/_poststart.sh ioc/myjail`, Also previously I was able to echo progress but latest version does not output anything on the screen.

**Comment by gronke** [comment]
This folder gets created with temporary scripts that are executed as `exec.start`, `exec.stop` and so on. Instead of execution preparation commands immediately, libiocage queues them and puts them in the required jail start hook.

There is one important hook missing: A hook on the host that fires when the JID is available. The currently last hook before `exec.start` that we can use is `exec.prestart` with the jail not running yet.

I'm awaiting feedback on https://reviews.freebsd.org/D15330 that would help recover the `IOCAGE_` env variables and several other things. On the other hand this would be the right time to switch from shell command execution to a cython module for libjail. 🤔

**Comment by urosgruber** [comment]
So if I understand this `IOCAGE_` variable are no-go until FreeBSD fix is approved? Not sure how will this work on older versions of FreeBSD.

And question about temporary scripts. Could this be security issue because content is visible from the jail?

**Comment by gronke** [comment]
> So if I understand this IOCAGE_ variable are no-go until FreeBSD fix is approved? Not sure how will this work on older versions of FreeBSD.

I'm investigating now if it is possible to create a Cython libjail wrapper in short terms. If that turns out to be no option, we'll have to partially recover the previous code that did everything manually. I'm not willing to give up the huge performance gain without fighting for it. 

https://github.com/iocage/libiocage/commit/ea759ea4e52a9f59f738c3f8c7083ff25917d596 is the last commit before the changes - @urosgruber stick on that one until you hear back here in case you rely on the feature. Another workaround would be to disable exec.start and manually execute from the exec.poststart:

```
ioc set exec.start=none myjail
ioc set exec.poststart="JID=\$(jls -j myjail jid) exec myjail /etc/sh -c 'echo $JID'" myjail
```

Think I can recover the env variables for `exec.poststart`, `exec.prestop`, `exec.stop` and `exec.poststop`.

> And question about temporary scripts. Could this be security issue because content is visible from the jail?

The directory is mounted read-only and all information can be either looked up on the jail, can be guessed or is considered public knowledge anyway. The only "private" information in the .env file is the  JID. I think the jail does not need to know about the host configuration anyway, so that only the required files should be mounted - I will change that.

**Comment by urosgruber** [comment]
@gronke for some reason latest version again broke this. No env variables on stop and start hooks. Not sure if something changed when I last checked.

**Comment by urosgruber** [comment]
@gronke So commit 2e13eb06cf5b459b23124028bb3d324d5e9e306c broke this functionality. Previous commit works, but everything after this is broken. I see some env changes so not really sure if this is supported with `ioc` cli or it's just in `libioc` for now.
