### ISSUE TITLE
The config property 'vnet0_mac' of jail ... is unknown.

### ISSUE THREAD

**Issue by pmhausen** [bsdci/libioc#516]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

```sh-session
root@jailhost:~ # ioc --version
ioc, version 0.3.0 2018/08/25

root@jailhost:~ # ioc set vnet0_mac="121508a4594e,121508a4594f" test130
The config property 'vnet0_mac' of jail 'test130' is unknown.
```

Expected result: configure jail's MAC address like we do with py-iocage.

I did clone master to install (I guess).

Kind regards
Patrick

**Comment by gronke** [comment]
The Jail configuration property still exists, but it is now dynamically matching your interface name rather than relying on them being called `vnet0` to `vnet4`. When you have an interface with an arbitrary name, for example `nic0`, you can set the property `nic0_mac`.

While writing this comment I've just noticed that this is no longer likely to work because libiocage became strict about jail properties. Because this issue targets the lack of documentation, I will create another one for restoring support of those properties.

**Comment by gronke** [comment]
#695 introduces unit tests for the MAC address input. A more generalized unit-test of the JailConfig properties will follow.
